# Ubuntu packages
- name: Add apt ppa repositories
  tags: packages
  become: yes
  apt_repository:
    repo: '{{ item }}'
    codename: bionic
    update_cache: no
    state: present
  with_items:
    - 'ppa:alessandro-strada/ppa' # For google-drive-ocamlfuse
    - 'ppa:atareao/flameshot' # Unofficial

- name: Add apt repo keys
  tags: packages
  become: yes
  apt_key:
    url: '{{ item }}'
    state: present
  with_items: '{{ repo_key_urls }}'

- name: Add deb repositories
  tags: packages
  become: yes
  apt_repository:
    update_cache: no
    repo: '{{ item }}'
    state: present
  with_items: "{{ debian_repos }}"

- name: Update apt cache
  tags: packages
  become: yes
  apt:
    update_cache: yes

- name: Install apt packages
  tags: packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }} + {{ debian_packages }}"

- name: Ensure docker is running and set to autostart
  become: yes
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add fuse group
  tags: user
  become: yes
  group:
    name: fuse
    state: present

- name: Make the aj user sudoer with no password (for rvm)
  tags: user
  become: yes
  lineinfile: "dest=/etc/sudoers state=present regexp='^aj' line='aj ALL=(ALL) NOPASSWD: ALL'"

- name: Install rvm
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_rubies:
      - 'ruby-2.4.1'
    rvm1_user: aj

# TODO: nvm

- name: Download and install docker-compose
  tags: packages
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.18.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0644
    owner: root
    group: root
