# Network manager applet
dbus-launch nm-applet &
# Filesystem daemon (auto-mounts flash drives, etc)
thunar --daemon &

# Launch awesomewm
mkdir -p ~/.cache
exec /usr/bin/awesome >> ~/.cache/awesome.stdout 2>> ~/.cache/awesome.stderr
