#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi  

source $HOME/dotfiles/bashrc

xorg_conf=$HOME/dotfiles/xorg

# Remap mouse buttons (side buttons as middle click)
$xorg_conf/remap_mouse_button.sh

# Load up our custom xmodmap
xmodmap $xorg_conf/xmodmap

# Set keyboard repeat delay to 400ms and repeat rate to 100
xset r rate 400 100

# Start a trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
 --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# Started by xmonad-session
# xmonad
