#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi  

xorg_conf=$HOME/dotfiles/xorg

$xorg_conf/remap_mouse_button.sh
xmodmap $xorg_conf/xmodmap
