---

- hosts: dev
  remote_user: aj
  become: yes
  any_errors_fatal: yes
  vars:
    common_packages:
      - 'git'
      - 'vim'
      - 'libreoffice'
      - 'gimp'
      - 'inkscape'
      - 'ghostscript'
      - 'google-drive-ocamlfuse'
      - 'flameshot'
      - 'screen'
      - 'ca-certificates'
      - 'curl'
      - 'xclip'
      - 's3cmd'
      - 'resilio-sync'
      - 'awesome'
      - 'smartmontools'
      - 'ansible'
      - 'yarn'

    debian_preload_packages:
      - 'apt-transport-https'
      - 'software-properties-common'

    debian_packages:
      - 'vim-gtk'
      - 'chromium-browser'
      - 'chromium-codecs-ffmpeg-extra'
      - 'silversearcher-ag'
      - 'imagemagick'
      - 'ttf-mscorefonts-installer'
      - 'wavebox'
      - 'fonts-inconsolata'
      - 'ssh'
      - 'zfs-dkms'
      - 'zfsutils-linux'
      - 'linux-headers-generic'

    fedora_preload_packages:
      - 'python2-libselinux'
      - 'python3-libselinux'

    fedora_packages:
      - 'vim-X11'
      - 'chromium'
      - 'the_silver_searcher'
      - 'ImageMagick'
      - 'Wavebox'
      - 'levien-inconsolata-fonts'
      - 'openssh-server'
      - 'kernel-devel'
      - 'xorg-x11-font-utils'
      - 'fontconfig'
      - 'wget'
      - 'cabextract'
      - 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
      - 'docker-ce'

    repo_key_urls:
      - 'https://wavebox.io/dl/client/repo/archive.key'
      - 'https://linux-packages.resilio.com/resilio-sync/key.asc'

  tasks:
    # Ubuntu packages
    - name: Install apt preload packages
      when: ansible_os_family == "Debian"
      apt:
        name: '{{ item }}'
        state: present
      with_items: '{{ debian_preload_packages }}'

    - name: Add apt ppa repositories
      when: ansible_os_family == "Debian"
      apt_repository:
        repo: '{{ item }}'
        codename: xenial
        update_cache: no
        state: present
      with_items:
        - 'ppa:klaus-vormweg/awesome' # Unofficial
        - 'ppa:ansible/ansible'
        - 'ppa:alessandro-strada/ppa' # For google-drive-ocamlfuse
        - 'ppa:atareao/flameshot' # Unofficial

    - name: Add apt repo keys
      when: ansible_os_family == "Debian"
      apt_key:
        url: '{{ item }}'
        state: present
      with_items: '{{ repo_key_urls }}'

    - name: Add deb repositories
      when: ansible_os_family == "Debian"
      apt_repository:
        update_cache: no
        repo: '{{ item }}'
        state: present
      with_items:
        - 'deb https://wavebox.io/dl/client/repo/ x86_64/'
        - 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free'

    - name: Update apt cache
      when: ansible_os_family == "Debian"
      apt:
        update_cache: yes

    - name: Install apt packages
      when: ansible_os_family == "Debian"
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }} + {{ debian_packages }}"

    # Fedora packages
    - name: Install selinux python bindings
      when: ansible_os_family == "RedHat"
      dnf:
        name: "{{ item }}"
        state: present
      with_items: '{{ fedora_preload_packages }}'

    - name: Add rpm keys
      when: ansible_os_family == "RedHat"
      rpm_key:
        key: '{{ item }}'
        state: present
      with_items: '{{ repo_key_urls }}'

    - name: Add dnf repos by url
      when: ansible_os_family == "RedHat"
      command: 'dnf config-manager --add-repo {{ item }}'
      with_items:
       - 'https://wavebox.io/dl/client/repo/yum/wavebox.repo'
       - 'https://dl.yarnpkg.com/rpm/yarn.repo'
       - 'https://download.docker.com/linux/fedora/docker-ce.repo'

    - name: Add dnf repo by copr
      when: ansible_os_family == "RedHat"
      command: dnf copr enable -y sergiomb/google-drive-ocamlfuse

    - name: Add dnf repos by file
      when: ansible_os_family == "RedHat"
      copy:
        src: ./fedora/resilio-sync.repo
        dest: /etc/yum.repos.d/resilio-sync.repo
        mode: 0644

    - name: Install dnf packages
      when: ansible_os_family == "RedHat"
      dnf:
        name: "{{ item }}"
        # Uncomment if docker-ce cannot be found (Fedora 28)
        #enablerepo: docker-ce-edge
        state: present
      with_items: "{{ common_packages }} + {{ fedora_packages }}"

    - name: Get rpm dist string
      when: ansible_os_family == "RedHat"
      args:
        warn: no
      command: rpm -E %dist
      register: rpm_dist

    - name: Install zfs rpm package
      when: ansible_os_family == "RedHat"
      dnf:
        name: "http://download.zfsonlinux.org/fedora/zfs-release{{rpm_dist.stdout}}.noarch.rpm"
        state: present

    # Common
    - name: Add fuse group
      group:
        name: fuse
        state: present

    - name: Use CLI login
      command: systemctl set-default multi-user.target

    - name: Start sshd at boot
      systemd:
        name: sshd
        state: started
        enabled: yes

