---

- hosts: dev
  remote_user: aj
  any_errors_fatal: yes

  tasks:
    - name: Flesh out aj user
      become: yes
      user:
        name: aj
        home: /home/aj
        move_home: yes
        shell: /bin/bash
        groups: ['adm', 'fuse']
        append: yes
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_comment: aj@dev
        ssh_key_type: rsa
        ssh_key_file: .ssh/id_rsa
        state: present

    - name: Clone dotfiles
      git:
        repo: 'https://github.com/arthurljones/dotfiles.git'
        dest: /home/aj/dotfiles
        version: master

    - name: Link dotfiles
      command: /home/aj/dotfiles/link_dotfiles.sh
      args:
        chdir: /home/aj

    - name: Install rvm
      become: yes
      include_role:
        name: rvm_io.ruby
      vars:
        rvm1_rubies:
          - 'ruby-2.4.1'
        rvm1_user: aj

    # TODO: nvm
    # TODO: awesomewm setup

