context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = output_common_sink
                node.description = "output-common-sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                media.class = Audio/Source
                node.name = output_common_source
                node.description = "output-common-source"
                audio.position = [ FL FR ]
            }
        }
    }

    {   name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = input_common_sink
                node.description = "input-common-sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                media.class = Audio/Source
                node.name = input_common_source
                node.description = "input-common-source"
                audio.position = [ FL FR ]
            }
        }
    }
]
